language: ruby
sudo: false
cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.4

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

before_install:
  - gem update --system
  - gem install bundler -v "1.17.3"

notifications:
  email: false
